In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-2.7976e+29,  4.5773e-41, -2.7976e+29],
        [ 4.5773e-41,  0.0000e+00,  0.0000e+00],
        [ 1.4013e-45,  1.6751e-37,  5.0447e-43],
        [ 0.0000e+00,  9.8091e-45,  0.0000e+00],
        [ 1.4252e+17,  4.5773e-41, -3.3615e-26]])


In [3]:
# Randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.7471, 0.7451, 0.0472],
        [0.4923, 0.7305, 0.1393],
        [0.5032, 0.2490, 0.3574],
        [0.0793, 0.9487, 0.7984],
        [0.4937, 0.1672, 0.6295]])


In [4]:
# Matrix with zeros and of dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Tensor from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# Create tensors based on existing ones. Properties such as dtype are reused.
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1482, -0.2711,  0.4375],
        [ 0.1952, -1.0167,  0.2907],
        [ 0.2659,  1.0546,  0.5482],
        [ 1.4840, -1.5415, -0.6439],
        [ 1.0879, -0.0119, -0.1256]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
x.shape

torch.Size([5, 3])

## Operations

In [9]:
# Addition, syntax 1
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.2986,  0.4924,  1.1718],
        [ 0.8864, -0.5729,  0.6410],
        [ 1.2403,  1.2249,  1.1488],
        [ 2.2812, -1.0076, -0.4578],
        [ 1.5791,  0.4949,  0.0548]])


In [10]:
# Addition, syntax 2
print(torch.add(x, y))

tensor([[ 0.2986,  0.4924,  1.1718],
        [ 0.8864, -0.5729,  0.6410],
        [ 1.2403,  1.2249,  1.1488],
        [ 2.2812, -1.0076, -0.4578],
        [ 1.5791,  0.4949,  0.0548]])


In [11]:
# With output tensor argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.2986,  0.4924,  1.1718],
        [ 0.8864, -0.5729,  0.6410],
        [ 1.2403,  1.2249,  1.1488],
        [ 2.2812, -1.0076, -0.4578],
        [ 1.5791,  0.4949,  0.0548]])


In [12]:
# Addition: in-place
y.add_(x)
print(y)

tensor([[ 0.2986,  0.4924,  1.1718],
        [ 0.8864, -0.5729,  0.6410],
        [ 1.2403,  1.2249,  1.1488],
        [ 2.2812, -1.0076, -0.4578],
        [ 1.5791,  0.4949,  0.0548]])


In [13]:
# Standard NumPy-like indexing
print(x[:, 1])

tensor([-0.2711, -1.0167,  1.0546, -1.5415, -0.0119])


In [14]:
x

tensor([[ 0.1482, -0.2711,  0.4375],
        [ 0.1952, -1.0167,  0.2907],
        [ 0.2659,  1.0546,  0.5482],
        [ 1.4840, -1.5415, -0.6439],
        [ 1.0879, -0.0119, -0.1256]])

In [15]:
# Resizing
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x

tensor([[-0.2032, -0.9599,  0.1918,  1.1014],
        [-1.1545, -1.3825, -0.0349, -0.0341],
        [-0.1133, -0.8152,  0.9171, -0.2255],
        [-1.7341,  0.2678, -0.5048,  0.2054]])

In [17]:
y

tensor([-0.2032, -0.9599,  0.1918,  1.1014, -1.1545, -1.3825, -0.0349, -0.0341,
        -0.1133, -0.8152,  0.9171, -0.2255, -1.7341,  0.2678, -0.5048,  0.2054])

In [18]:
z

tensor([[-0.2032, -0.9599,  0.1918,  1.1014, -1.1545, -1.3825, -0.0349, -0.0341],
        [-0.1133, -0.8152,  0.9171, -0.2255, -1.7341,  0.2678, -0.5048,  0.2054]])

In [19]:
# If you have a one-element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1895])
0.18948926031589508


**Read later:**


100+ Tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random numbers, etc.,
are described [here](https://pytorch.org/docs/torch)

# NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

## Converting a Torch Tensor to a NumPy Array

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

# CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

In [25]:
# Let's run this cell only if CUDA is available
# We will use `torch.device` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)   # create a tensor on GPU
    x = x.to(device)                        # or move it
    z = x + y
    print(z)
    print(z.to("cpu"), torch.double)        # .to can also change dtype at the same time

tensor([1.1895], device='cuda:0')
tensor([1.1895]) torch.float64
